// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AddEventRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            string   `protobuf:"bytes,3,opt,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            string   `protobuf:"bytes,4,opt,name=exercises,proto3" json:"exercises,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	ExpectedFinishTime   string   `protobuf:"bytes,7,opt,name=expectedFinishTime,proto3" json:"expectedFinishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventRequest) Reset()         { *m = AddEventRequest{} }
func (m *AddEventRequest) String() string { return proto.CompactTextString(m) }
func (*AddEventRequest) ProtoMessage()    {}
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *AddEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventRequest.Unmarshal(m, b)
}
func (m *AddEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventRequest.Marshal(b, m, deterministic)
}
func (m *AddEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventRequest.Merge(m, src)
}
func (m *AddEventRequest) XXX_Size() int {
	return xxx_messageInfo_AddEventRequest.Size(m)
}
func (m *AddEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventRequest proto.InternalMessageInfo

func (m *AddEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *AddEventRequest) GetFrontends() string {
	if m != nil {
		return m.Frontends
	}
	return ""
}

func (m *AddEventRequest) GetExercises() string {
	if m != nil {
		return m.Exercises
	}
	return ""
}

func (m *AddEventRequest) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *AddEventRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *AddEventRequest) GetExpectedFinishTime() string {
	if m != nil {
		return m.ExpectedFinishTime
	}
	return ""
}

type AddTeamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventTag             string   `protobuf:"bytes,2,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTeamRequest) Reset()         { *m = AddTeamRequest{} }
func (m *AddTeamRequest) String() string { return proto.CompactTextString(m) }
func (*AddTeamRequest) ProtoMessage()    {}
func (*AddTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *AddTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeamRequest.Unmarshal(m, b)
}
func (m *AddTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeamRequest.Marshal(b, m, deterministic)
}
func (m *AddTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeamRequest.Merge(m, src)
}
func (m *AddTeamRequest) XXX_Size() int {
	return xxx_messageInfo_AddTeamRequest.Size(m)
}
func (m *AddTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeamRequest proto.InternalMessageInfo

func (m *AddTeamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddTeamRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

func (m *AddTeamRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTeamRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InsertResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (m *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(m, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

func (m *InsertResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InsertResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventResponse struct {
	Events               []*GetEventResponse_Events `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	ErrorMessage         string                     `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

func (m *GetEventResponse) GetEvents() []*GetEventResponse_Events {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *GetEventResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventResponse_Events struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            string   `protobuf:"bytes,3,opt,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            string   `protobuf:"bytes,4,opt,name=exercises,proto3" json:"exercises,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	StartedAt            string   `protobuf:"bytes,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	ExpectedFinishTime   string   `protobuf:"bytes,8,opt,name=expectedFinishTime,proto3" json:"expectedFinishTime,omitempty"`
	FinishedAt           string   `protobuf:"bytes,9,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse_Events) Reset()         { *m = GetEventResponse_Events{} }
func (m *GetEventResponse_Events) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse_Events) ProtoMessage()    {}
func (*GetEventResponse_Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4, 0}
}

func (m *GetEventResponse_Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse_Events.Unmarshal(m, b)
}
func (m *GetEventResponse_Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse_Events.Marshal(b, m, deterministic)
}
func (m *GetEventResponse_Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse_Events.Merge(m, src)
}
func (m *GetEventResponse_Events) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse_Events.Size(m)
}
func (m *GetEventResponse_Events) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse_Events.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse_Events proto.InternalMessageInfo

func (m *GetEventResponse_Events) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEventResponse_Events) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetEventResponse_Events) GetFrontends() string {
	if m != nil {
		return m.Frontends
	}
	return ""
}

func (m *GetEventResponse_Events) GetExercises() string {
	if m != nil {
		return m.Exercises
	}
	return ""
}

func (m *GetEventResponse_Events) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *GetEventResponse_Events) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *GetEventResponse_Events) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *GetEventResponse_Events) GetExpectedFinishTime() string {
	if m != nil {
		return m.ExpectedFinishTime
	}
	return ""
}

func (m *GetEventResponse_Events) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

type GetEventTeamsRequest struct {
	EventTag             string   `protobuf:"bytes,1,opt,name=eventTag,proto3" json:"eventTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventTeamsRequest) Reset()         { *m = GetEventTeamsRequest{} }
func (m *GetEventTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsRequest) ProtoMessage()    {}
func (*GetEventTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *GetEventTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsRequest.Unmarshal(m, b)
}
func (m *GetEventTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsRequest.Merge(m, src)
}
func (m *GetEventTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsRequest.Size(m)
}
func (m *GetEventTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsRequest proto.InternalMessageInfo

func (m *GetEventTeamsRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

type GetEventTeamsResponse struct {
	Teams                []*GetEventTeamsResponse_Teams `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	ErrorMessage         string                         `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetEventTeamsResponse) Reset()         { *m = GetEventTeamsResponse{} }
func (m *GetEventTeamsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsResponse) ProtoMessage()    {}
func (*GetEventTeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *GetEventTeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsResponse.Unmarshal(m, b)
}
func (m *GetEventTeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsResponse.Merge(m, src)
}
func (m *GetEventTeamsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsResponse.Size(m)
}
func (m *GetEventTeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsResponse proto.InternalMessageInfo

func (m *GetEventTeamsResponse) GetTeams() []*GetEventTeamsResponse_Teams {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *GetEventTeamsResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventTeamsResponse_Teams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastAccess           string   `protobuf:"bytes,5,opt,name=last_access,json=lastAccess,proto3" json:"last_access,omitempty"`
	SolvedChallenges     string   `protobuf:"bytes,6,opt,name=solved_challenges,json=solvedChallenges,proto3" json:"solved_challenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventTeamsResponse_Teams) Reset()         { *m = GetEventTeamsResponse_Teams{} }
func (m *GetEventTeamsResponse_Teams) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsResponse_Teams) ProtoMessage()    {}
func (*GetEventTeamsResponse_Teams) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6, 0}
}

func (m *GetEventTeamsResponse_Teams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Unmarshal(m, b)
}
func (m *GetEventTeamsResponse_Teams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsResponse_Teams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsResponse_Teams.Merge(m, src)
}
func (m *GetEventTeamsResponse_Teams) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Size(m)
}
func (m *GetEventTeamsResponse_Teams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsResponse_Teams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsResponse_Teams proto.InternalMessageInfo

func (m *GetEventTeamsResponse_Teams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetLastAccess() string {
	if m != nil {
		return m.LastAccess
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetSolvedChallenges() string {
	if m != nil {
		return m.SolvedChallenges
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AddEventRequest)(nil), "AddEventRequest")
	proto.RegisterType((*AddTeamRequest)(nil), "AddTeamRequest")
	proto.RegisterType((*InsertResponse)(nil), "InsertResponse")
	proto.RegisterType((*GetEventResponse)(nil), "GetEventResponse")
	proto.RegisterType((*GetEventResponse_Events)(nil), "GetEventResponse.Events")
	proto.RegisterType((*GetEventTeamsRequest)(nil), "GetEventTeamsRequest")
	proto.RegisterType((*GetEventTeamsResponse)(nil), "GetEventTeamsResponse")
	proto.RegisterType((*GetEventTeamsResponse_Teams)(nil), "GetEventTeamsResponse.Teams")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0x38, 0x89, 0x27, 0x90, 0xa4, 0xab, 0x16, 0x59, 0x26, 0x82, 0xc8, 0xa7, 0x48,
	0x08, 0x83, 0xc2, 0x0b, 0x10, 0xa1, 0x82, 0x38, 0xc0, 0xc1, 0xe4, 0x1e, 0x6d, 0xed, 0x69, 0x6a,
	0xc9, 0xb1, 0xcd, 0xce, 0x12, 0xda, 0x33, 0x6f, 0xc0, 0x0b, 0xf0, 0x04, 0x3c, 0x0d, 0x67, 0x1e,
	0x05, 0x09, 0x79, 0xbd, 0x76, 0x7e, 0xea, 0x4a, 0x3d, 0xf6, 0xe6, 0xef, 0x9b, 0x59, 0xef, 0xce,
	0x7c, 0xdf, 0x0c, 0x0c, 0x48, 0x66, 0x02, 0xfd, 0x5c, 0x64, 0x32, 0xf3, 0x7a, 0x60, 0x9d, 0x6f,
	0x72, 0x79, 0xe3, 0xfd, 0x35, 0x60, 0xb4, 0x88, 0xa2, 0xf3, 0x2d, 0xa6, 0x32, 0xc0, 0xaf, 0xdf,
	0x90, 0x24, 0x63, 0xd0, 0x49, 0xf9, 0x06, 0x1d, 0x63, 0x6a, 0xcc, 0xec, 0x40, 0x7d, 0xb3, 0x31,
	0xb4, 0x25, 0x5f, 0x3b, 0xa6, 0xa2, 0x8a, 0x4f, 0x36, 0x01, 0xfb, 0x52, 0x64, 0xa9, 0xc4, 0x34,
	0x22, 0xa7, 0xad, 0xf8, 0x1d, 0x51, 0x44, 0xf1, 0x1a, 0x45, 0x18, 0x13, 0x92, 0xd3, 0x29, 0xa3,
	0x35, 0x51, 0x44, 0xf9, 0x96, 0xc7, 0x09, 0xbf, 0x48, 0xd0, 0xb1, 0xa6, 0xc6, 0xcc, 0x0a, 0x76,
	0x04, 0x73, 0xa1, 0x1f, 0xf2, 0x9c, 0x87, 0xb1, 0xbc, 0x71, 0xba, 0x2a, 0x58, 0x63, 0xe6, 0x03,
	0xc3, 0xeb, 0x1c, 0x43, 0x89, 0xd1, 0xfb, 0x38, 0x8d, 0xe9, 0x6a, 0x19, 0x6f, 0xd0, 0xe9, 0xa9,
	0x0b, 0x1a, 0x22, 0xde, 0x0f, 0x03, 0x86, 0x8b, 0x28, 0x5a, 0x22, 0xdf, 0x54, 0xe5, 0x0d, 0xc1,
	0x8c, 0x23, 0x5d, 0x9c, 0x19, 0x47, 0xec, 0x29, 0xd8, 0x58, 0x94, 0xbf, 0xda, 0x15, 0xd8, 0x57,
	0xc4, 0x92, 0xaf, 0xd9, 0x29, 0x58, 0xb8, 0xe1, 0x71, 0xa2, 0x2b, 0x2c, 0x41, 0xdd, 0xa1, 0xce,
	0x5e, 0x87, 0x5c, 0xe8, 0xe7, 0x9c, 0xe8, 0x7b, 0x26, 0x22, 0x55, 0x92, 0x1d, 0xd4, 0xd8, 0xfb,
	0x0c, 0xc3, 0x8f, 0x29, 0xa1, 0x90, 0x01, 0x52, 0x9e, 0xa5, 0x84, 0xcc, 0x81, 0xde, 0x27, 0x24,
	0xe2, 0xeb, 0xaa, 0xcd, 0x15, 0x64, 0x1e, 0x3c, 0x42, 0x21, 0x32, 0x51, 0x85, 0xcb, 0x17, 0x1d,
	0x70, 0xde, 0x3f, 0x13, 0xc6, 0x1f, 0x50, 0x6a, 0xd5, 0xf4, 0x2f, 0x5f, 0x43, 0x57, 0x3d, 0x9b,
	0x1c, 0x63, 0xda, 0x9e, 0x0d, 0xe6, 0x8e, 0x7f, 0x9c, 0xe2, 0x2b, 0x44, 0x81, 0xce, 0xbb, 0xcf,
	0x55, 0xee, 0x4f, 0x13, 0xba, 0xe5, 0xb1, 0x07, 0xed, 0x8b, 0x09, 0xd8, 0x24, 0xb9, 0x90, 0x18,
	0x2d, 0xa4, 0xb6, 0xc3, 0x8e, 0xb8, 0xc3, 0x35, 0xfd, 0xbb, 0x5c, 0xc3, 0x9e, 0x01, 0x5c, 0x2a,
	0xa4, 0x7e, 0x67, 0xab, 0xbc, 0x3d, 0xc6, 0x9b, 0xc3, 0x69, 0xd5, 0xdb, 0xc2, 0x59, 0x54, 0x59,
	0xcb, 0x85, 0xda, 0x39, 0xba, 0x4b, 0x35, 0xf6, 0x7e, 0x99, 0x70, 0x76, 0x74, 0x48, 0x0b, 0x37,
	0x07, 0x4b, 0x16, 0x84, 0xd6, 0x6d, 0xe2, 0x37, 0xa6, 0xf9, 0x25, 0x2a, 0x53, 0xef, 0x25, 0xdd,
	0x6f, 0x03, 0x2c, 0x75, 0xe8, 0x96, 0xe5, 0x6b, 0x57, 0x9b, 0x4d, 0xae, 0x6e, 0xef, 0xe9, 0x3b,
	0x01, 0x3b, 0x14, 0xc8, 0xcb, 0xbe, 0x6a, 0xbd, 0x6a, 0x82, 0x3d, 0x87, 0x41, 0xc2, 0x49, 0xae,
	0x78, 0x18, 0x22, 0x91, 0xb6, 0x3d, 0x14, 0xd4, 0x42, 0x31, 0xec, 0x05, 0x9c, 0x50, 0x96, 0x6c,
	0x31, 0x5a, 0x85, 0x57, 0x3c, 0x49, 0x30, 0x5d, 0x23, 0x29, 0xed, 0xec, 0x60, 0x5c, 0x06, 0xde,
	0xd5, 0xfc, 0xfc, 0x8f, 0x01, 0xd6, 0x97, 0x62, 0x49, 0xb1, 0x57, 0xd0, 0xaf, 0x96, 0x12, 0x1b,
	0xfb, 0x47, 0xfb, 0xc9, 0x1d, 0xf9, 0x87, 0xc3, 0xe4, 0xb5, 0xd8, 0x4b, 0xe8, 0xe9, 0x29, 0x67,
	0x23, 0xff, 0x70, 0xde, 0x9b, 0xd2, 0x67, 0x60, 0x57, 0x3d, 0x26, 0xd6, 0xf5, 0xd5, 0x2a, 0x74,
	0x4f, 0x6e, 0xcd, 0x8b, 0xd7, 0x62, 0x6f, 0xe1, 0xf1, 0x81, 0x1a, 0xec, 0xcc, 0x6f, 0x52, 0xde,
	0x7d, 0xd2, 0x2c, 0x9a, 0xd7, 0xba, 0xe8, 0xaa, 0x8d, 0xfb, 0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x63, 0xc4, 0xcb, 0xc0, 0x80, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	//Insert
	AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	//Select
	GetEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetEventResponse, error)
	GetEventTeams(ctx context.Context, in *GetEventTeamsRequest, opts ...grpc.CallOption) (*GetEventTeamsResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/Store/AddEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/Store/AddTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, "/Store/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetEventTeams(ctx context.Context, in *GetEventTeamsRequest, opts ...grpc.CallOption) (*GetEventTeamsResponse, error) {
	out := new(GetEventTeamsResponse)
	err := c.cc.Invoke(ctx, "/Store/GetEventTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	//Insert
	AddEvent(context.Context, *AddEventRequest) (*InsertResponse, error)
	AddTeam(context.Context, *AddTeamRequest) (*InsertResponse, error)
	//Select
	GetEvents(context.Context, *Empty) (*GetEventResponse, error)
	GetEventTeams(context.Context, *GetEventTeamsRequest) (*GetEventTeamsResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) AddEvent(ctx context.Context, req *AddEventRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEvent not implemented")
}
func (*UnimplementedStoreServer) AddTeam(ctx context.Context, req *AddTeamRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeam not implemented")
}
func (*UnimplementedStoreServer) GetEvents(ctx context.Context, req *Empty) (*GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedStoreServer) GetEventTeams(ctx context.Context, req *GetEventTeamsRequest) (*GetEventTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventTeams not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/AddEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddEvent(ctx, req.(*AddEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/AddTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddTeam(ctx, req.(*AddTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetEventTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetEventTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/GetEventTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetEventTeams(ctx, req.(*GetEventTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvent",
			Handler:    _Store_AddEvent_Handler,
		},
		{
			MethodName: "AddTeam",
			Handler:    _Store_AddTeam_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Store_GetEvents_Handler,
		},
		{
			MethodName: "GetEventTeams",
			Handler:    _Store_GetEventTeams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
